- Universal FE Randomizer/src/fedata/gba/GBAFECharacterData.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Character.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Character.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Character.java
- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #35 - Fixed an issue where the lord flag was not assigned appropriately to a character if class randomization was disabled.
> [Issue #35] Fixed lord flag not being set if class randomization is not enabled.

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #31 - Fixed an issue where recruitable enemies can spawn with player-only weapons (i.e. berserk weapons).
> [Issue #31] Restricted recruitable enemies from receiving player-only weapons.

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4BloodRandomizer.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
- Universal FE Randomizer/src/ui/fe4/FE4ClassesView.java
* Redid the logic for restricted blood and added Quan's blood to the restricted list as well as his holy weapon to the no-inheritence list.
* Redid the logic for assigning holy blood to allow any character to have any holy blood, but only those with non-restricted blood have a chance to receive holy weapons.
* Increased the chance of holy weapons appearing in player conversations from 50% to 80% to compensate for the above change.
Fixed #32, #29, and #38.
> [Issue #29] [Issue #32] [Issue #38] Rewrote logic for restricted blood

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
Fixed #28 - Removed Altena from the analogue case, since her class is already limited to begin with (and her class doesn't really match with Quan's anyway).
> [Issue #28] Removed Gen 1 Analogue for Altena

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
Fixed #40 - Fixed an issue where Arvis's limited holy blood list wasn't being applied.
> [Issue #40] Fixed Arvis's blood limitations

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4BloodRandomizer.java
Fixed #41 - Added logic to ensure holy weapons are only given out if the holy blood for a character matches their weapon usage.
> [Issue #41] Holy Weapons restricted to matching class

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
Fixed #26 
* Added special case for item 0x2 to be set post randomization to be of something Leif and Ethlyn can use (when possible possible).
* Replaced 0x67 in Jeanne/Nanna's starting inventory with 0x40 and left 0x67 unrandomized.
> [Issue #26] Fixed issues with 0x2 and 0x67 in FE4.

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #57 - Fixed an issue where using the Match Parents (Loose) option causes a null pointer exception when procesing Altena (and her not having an analogue assigned).
> [Issue #57] Fixed NullPointerException in Loose child class matching

- Universal FE Randomizer/src/ui/fe4/FE4PromotionView.java
Fixed #63 - Fixed an issue where no promotion options were being selected on the first time on FE4 randomization.
> [Issue #63] Fixed a case where promotion options weren't defaulting to any option in FE4.

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4EnemyBuffer.java
Fixed #56 - Remove Sigurd's holy weapon from the pool of droppable boss holy weapons in gen 1.
> [Issue #56] Blacklist Sigurd's holy weapon from dropping a second copy in Gen 1.

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
- Universal FE Randomizer/src/random/snes/fe4/loader/ClassDataLoader.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
Fixed #62 - Added logic to give sages A rank light magic to preserve Light Priestess promotion ranks.
> [Issue #62] Give A rank Light magic to sages naturally

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #39 
* Updated castle guards list with Donovan, Zagam, Daggon, and Baran.
* Blacklisted melee staves from castle guards.
* Added Warp and Return staves to player-only items.
> [Issue #39] Removed Return and Warp from enemies and melee staves from castle guards.

- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
Fixed #65 - Retain Murgleis, Maltet, and the Saint's Staff in Yodel's inventory in FE6.
> [Issue #65] Retain holy weapons in FE6 in Yodel's inventory.

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Maybe fixed #72 - Fixed an issue where blacklisted characters (those not eligible for class randomization) were not being recorded for future reference.
> [Issue #72] Fixed blacklisted characters not being recorded

- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/WeaponsRandomizer.java
- Universal FE Randomizer/src/ui/WeaponEffectSelectionView.java
- Universal FE Randomizer/src/ui/WeaponsView.java
- Universal FE Randomizer/src/ui/model/WeaponEffectOptions.java
- Universal FE Randomizer/src/ui/model/WeaponOptions.java
Fixed #68.
* Added a control to specify what fraction of weapons gain special effects.
* Removed "None" from the list of effects possible (since the new control can set that now).
> [Feature #68] Added control for random effect chance

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
- Universal FE Randomizer/src/ui/fe4/FE4ClassOptions.java
- Universal FE Randomizer/src/ui/fe4/FE4ClassesView.java
Fixed #44 
Added a Blood Shuffling option for FE4. This option is unique in that it has some prerequisites.
Requires:
* Randomize Playable Characters ON
* Randomize Bosses ON
On top of that, selecting shuffle on playable characters or bosses will automatically toggle the other setting to Shuffle as well, as this only makes sense when both are shuffling. If either one is selected otherwise, shuffle will also be deselected in the other case.
> [Feature #44] Holy Blood Shuffling

- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFECharacterProvider.java
- Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java
- Universal FE Randomizer/src/random/gba/loader/PaletteLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/PaletteHelper.java
- Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
- Universal FE Randomizer/src/ui/MainView.java
- Universal FE Randomizer/src/ui/RecruitmentView.java
- Universal FE Randomizer/src/ui/model/RecruitmentOptions.java
Fixed #67 - Added the option to include creature campaign NPCs (Fado, Glen, Hayden, and Ismaire) to the pool for random recruitment.
> [Feature #67] Include Creature Campaign in Randomized Recruitment

- Universal FE Randomizer/src/random/gba/randomizer/EnemyBuffer.java
Fixed #93 - Fixed an issue where the option to buff enemies with a scaling buff wasn't applying the correct multiplier.
> [Issue #93] Fixed Enemy Scaling Buff

- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/general/WeaponRank.java
- Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java
- Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #96 
* Fixed an issue where the option to match rank was allowing lower ranked weapons. This logic has been updated to prioritize items that match rank and only fall back to lower ranks if the item is not available.
Additionally:
* Fixed an issue where later joining characters could join with lower weapon ranks than expected if they transfer more weapon ranks than necessary for their target class.
* Fixed an issue where some unwanted randomization in weapon rank assignment could occur when using the same seed.
* Added logic to show weapon rank assignments for characters in the changelog.
> [Issue #96] Fixed Match Rank option for Weapon Assignment

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
Fixed #78 - Added a fix for Knight Lord's map sprite to not be unique to Sigurd.
> [Feature #78] Knight Lord Map Sprite

- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #88 - Modified class randomization so that absolute CON is not transferred into the new class.
Old Behavior:
Sophia|Shaman|->|Axe Fighter
-|-|-|-
Personal CON|0||-8
Class CON|3||11
Effective CON|3|=|3
Barth|Knight|->|Pegasus Knight
-|-|-|-
Personal CON|3||11
Class CON|13||5
Effective CON|16|=|16
New Behavior:
Sophia|Shaman|->|Axe Fighter
-|-|-|-
Personal CON|0|=|0
Class CON|3||11
Effective CON|3||11
Barth|Knight|->|Pegasus Knight
-|-|-|-
Personal CON|3|=|3
Class CON|13||5
Effective CON|16||8
> [Feature #88] Class Randomization - CON now fits the target class instead of being transferred from the old class

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
Fixed #112 - Added special logic to make sure Julia, if selected to not be randomized, still gets Nihil at a minimum for the final chapter.
> [Issue #112] Give Julia Nihil if not randomized

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
Fixed #113 - It's possible for Lex to pick up a holy weapon from his lone event with the Brave Axe. This axe normally ends up on Schmidt if it's not passed down, which causes Schmidt to have a holy weapon in Chapter 6 and potentially have a weapon he shouldn't be able to use. This change links Lex and Schmidt's class to make sure they share weapon types, but it also blacklists holy weapons from Lex's events.
> [Issue #113] Added link between Lex and Schmidt with the Brave Axe.

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
Fixed #114 - Added Chapter 1 Marpha pursuit squad to the do-not-touch list for minions, to allow Dew and Edain to escape.
> [Feature #114] Let Dew and Edain consistently escape Marpha

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4BloodRandomizer.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
- Universal FE Randomizer/src/ui/MainView.java
- Universal FE Randomizer/src/ui/fe4/HolyBloodOptions.java
- Universal FE Randomizer/src/ui/fe4/HolyBloodView.java
Fixed #104 
Added several new options for randomizing holy blood bonuses including the ability to set the chunk size when distributing growth bonuses, the ability to set a baseline HP growth rate, and the ability to limit duplicates in blood bonus distribution between different blood types. Also added the ability to allow holy blood to receive bonuses that may not match the weapon type.
> [Feature #104] Expanded the options available for randomizing holy blood bonuses.

- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
Fixed #124 - Added logic to let promoted units promote into themselves if they ever are forced to promote. In the case of FE7 and FE8, this unit gains promotion bonuses again. This relies on the fact that no promotion items are coded to be usable for promoted classes, so the only time this applies is if the lord has scripted promotions.
> [Issue #124] Fixed forced promotions

- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java
Fixed #118 
* Fixed an issue where staves were not being considered valid items for sidegrading.
* Fixed an issue where FE8 Shamans were mistakenly including staves in their list of weapons.
> [Issue #118] Fixed issues with minion inventory being empty/invalid

- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
Fixed #135 - Fixed an issue where FE7 fails randomization if recruitment is randomized but lords are not randomized.
> [Issue #135] Fix FE7 Random Recruitment failure when not randomizing lords

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4BloodRandomizer.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
Fixed #133.
* Fixed an issue where STR/MAG adjust when randomizing classes was interfering with the growth transfer when allowing blood to randomize. 
* Fixed an issue where it was possible to end up with 0 growth unintentionally if blood growth bonuses are randomized.
> [Issue #133] Fixed conflicts with character growths and blood bonuses

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #134  - Fixed an issue where a the randomizer can fail to find an equivalent weapon for characters that have very limited weapon choices. In the worst case scenario, if there are no usable weapons, the character will retain the original weapon (though this should be considered an unhandled case).
> [Issue #134] Fixed randomization failure for strict item assignment

- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #139 - Added logic to prioritize the melee/ranged constraint over the strict/loose matching constraint. This should resolve the issue where characters that are supposed to have melee or ranged weapons may end up with one that isn't the correct type and softlocking the game, due to trying to match the original weapon.
> [Issue #139] Prioritize Melee/Ranged constraint over Strict/Loose Matching

- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #136 - Fixed an issue where retaining personal bases can end up with negative base stats (underflow) for characters that have negative personal bases.
> [Issue #136] Fixed base stat underflow

- Universal FE Randomizer/src/fedata/gba/GBAFECharacterData.java
- Universal FE Randomizer/src/fedata/gba/GBAFEClassData.java
- Universal FE Randomizer/src/fedata/gba/GBAFEItemData.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Character.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Class.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Item.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Character.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Class.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Item.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Character.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Class.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Item.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFECharacterProvider.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFEItemProvider.java
- Universal FE Randomizer/src/fedata/general/FEPrintableData.java
- Universal FE Randomizer/src/random/gba/loader/ChapterLoader.java
- Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java
- Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #142.
* Added logic to pull in class ranks when determining usable weapons for bosses. This resolves Paul and Jasmine (and a few other characters) not having weapon ranks coded into their character data, instead relying on class defaults.
* Added logic to pull in character ranks when determining usable weapons for minions. Minions generally rely on class data, but in some instances, they rely on specially coded character data for the specific character.
* Modified logic to default all classes to A rank in their weapon ranks. This has no effect on characters that specify their own weapon rank data (as most playable characters do) since those will overwrite the class defaults. This simplifies transferring higher rank weapons (B and A rank). Some enemies in the game can use these high …
> [Issue #142] Fixed Strict Matching for Enemy Inventory

- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #151 (depends on #152).
Applied the same logic as minion randomization when dealing with inventory changes to randomized recruitment. That is to say, take into account the source class's weapon rank defaults in addition to the character's weapon ranks to determine the real set of weapon ranks for a character.
> [Issue #151] Strict Matching fixes for Randomized Recruitment

- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/general/PaletteColor.java
Fixed #137 - Went though all of the FE7 battle animations and remapped all the color indices to more accurately translate palettes between classes.
Also fixed an issue where duplicate colors in the palettes were causing color crushing when translating some palettes.
> [Issue #137] Re-mapped color indices for FE7 class sprites

- Universal FE Randomizer/src/random/gba/randomizer/EnemyBuffer.java
Fixed #154 - Updated logic to cap minion weapon ranks at A rank to avoid hit and crit bonuses. Buffing minion weapons only goes up to A rank at max.
> [Issue #154] Capped minion ranks at A instead of S

- Universal FE Randomizer/src/random/gba/randomizer/EnemyBuffer.java
- Universal FE Randomizer/src/ui/EnemyBuffsView.java
Fixed #141 - Capped the maximum enemy growth rate for any single area to 127, as the value underflows above that in the autoleveling routine.
> [Issue #141] Capped enemy growths at 127% in any single area

- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9EnemyBuffer.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9Randomizer.java
Fixed #199 - Fixed an issue where assigning a heron to a class would crash due to having no weapon types available. Also made it so that if an exception is thrown during randomization, it notifies the user instead of appearing stuck.
> [Issue #199] Fixed hanging on randomizing classes for FE9

- Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #174 - Fixed several issues with FE4 bosses getting weapons they can't use in the second generation. Turns out, there are quite a few more weapons that aren't documented as being droppable, presumably because nobody ever not inherited them, like Finn's Brave Lance.
Also fixed a somewhat related issue where randomizing a weapon that is the same as the dropped weapon did not update the dropped item, resulting in a character having two weapons when they normally have one, which can cause issues if the weapon that was left over is unusable by the new class.
> [Issue #174] Fixed FE4 Gen 2 bosses getting unusable weapons.

- Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #181 - Reworked the autoleveling routine for randomized recruitment in GBAFE. The previous logic didn't quite calculate the changes correctly when jumping between promoted and unpromoted classes. The new one takes a more logical approach by operating with effective values instead of strictly the character bases. 
This does change a little bit for Karel in a specific case. The existing reverse recruitment patch balanced Karel a bit by starting him with 8 HP, 2 STR, and 5 SKL specifically. Given his growths, there's no natural mathematical way of getting this. So instead of coming up with stats for each possible place he could be recruited at, the logic now just ensures that HP, for any character, can never be below 10 HP (this is so they don't die immediately when entering combat). …
> [Issue #181] Reworked GBAFE autoleveling in Random Recruitment

- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFECharacterProvider.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFEItemProvider.java
- Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java
- Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/EnemyBuffer.java
- Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #185 - Added a way to restrict GBA weapons to being player only and added FE6 staves to the player only list. This mechanism exists for all of the GBA games, but only FE6 has weapons (more accurately, staves) added.
> [Issue #185] Added player only weapon list for GBAFE

- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFECharacterProvider.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFEClassProvider.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFEItemProvider.java
- Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java
- Universal FE Randomizer/src/random/gba/loader/ClassDataLoader.java
- Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/EnemyBuffer.java
- Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #193 - This restricts any character that starts off as an enemy from being any classes marked as being player only. These are generally classes the AI may not know how to deal with, which can cause freezing if the AI gets a hold of them.
Should be merged after PR #203
> [Issue #193] Restrict recruitable characters to AI-friendly classes.

- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #189 - Updated logic when randomizing bosses to ensure they default to the highest rank they normally have for all weapons. This simplifies weapon assignment and makes sure that they can use the any sidegrade weapon. For example, Cameron is normally a Paladin with B swords, B Lances, and C axes. If he were to change to a Falconknight, he previously would have B rank in one of the weapons and C rank in the other. With this change, he now would have B rank in both, preventing the possibility of him receiving a weapon that he cannot use.
> [Issue #189] Updated boss weapon ranks logic when randomizing boss classes

- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
Fixed #167 - Fixed an issue where "NONE" was considered a valid affinity. If this was assigned to a playable character with a support level, it will use garbage data to determine the bonuses, usually resulting in hilarious results.
> [Issue #167] Fixed null affinities

- Universal FE Randomizer/src/ui/WeaponsView.java
Fixed #176 - Updated the maximum weapon durability selectable for GBAFE to be 63. This is due to a limitation of the save format for GBAFE games. They seem to only use 6 bits to save durability information for weapons in the save data. This means that any weapon that attempts to save its durability will have its most significant 2 bits cut off. Based on empirical testing, 6 bits seems to be saved, as a 99 durability weapon, when saved, will load as having 35 durability. (99 is 0x63 in hex. If you truncate the two most significant bits, you get 0x23, which is 35 in decimal.)
> [Issue #176] Reduced maximum durability for GBAFE

- Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #175 - Fixed an issue where Creature Campaign characters in FE8 could not have their recruitment randomized due to the NPC variants of their class being unrecognized.
> [Issue #175] Fixed FE8 Creature Campaign recruitment

- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/general/PaletteColor.java
- Universal FE Randomizer/src/fedata/gba/general/PaletteV2.java
- Universal FE Randomizer/src/random/gba/loader/PaletteLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
Fixed #165 - Added logic to not do unnecessary work by not generating palettes if characters are not actually changing classes. This should resolve issues where characters have new palettes even if their class has not changed.
Additionally, I updated the logic to always strip out duplicate colors from the list of reference colors. This should result in better color choices in most cases. There were also some minor issues with color indices in FE8 (specifically in the lord palettes and Paladin). There might be more, but we can tackle them as they come.
Also to help, changelogs now have a debug section for palette changes at the end of the log, with colors and their RGB values used.
> [Issue #165] Fixing palettes. Again.

- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9Randomizer.java
Fixed #204 - Added logic to remove KEY0 from Sothe personally and apply it as needed to any playable character that becomes a Thief. KEY50 remains on Volke for a guaranteed unlocker (albeit at 50G for every lock). With this change, every thief should be able to unlock doors and chests for free, but Volke can always unlock doors and chests for 50G, regardless of his class. This change only applies if Thieves are included in Player Character randomization.
> [Issue #204] Assign KEY0 skill as necessary.

- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ClassDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java
Fixed #215 - Fixed an issue where staff sages were being assigned light magic based off of their staff rank. Added a proper check to determine light magic usage (i.e. check the class for the Lumina skill, instead of assuming promoted staff users could use Light magic).
> [Issue #215] Fixed light magic assignment

- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9SkillDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9SkillRandomizer.java
Fixed #217 - Added support to make sure we don't ignore occult skills during skill randomization. Including Occult skills when randomizing skills (or buffing enemies) will come later. This simply makes sure the occult skill switches to match the class.
> [Issue #217] Basic Occult Skill Support

- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9EnemyBuffer.java
Fixed #217 - Apparently FE9's engine is smart enough to know to give minions the appropriate weapon ranks to accommodate their weapon when they are loaded in, so there's no longer a need to set weapon ranks for classes. Instead, the class weapon ranks seem to force a promoted character to have at least that rank. This should fix the issue where every class always immediately got S ranks in everything.
> [Issue #217] Removed S weapon ranks for all classes.

- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9Randomizer.java
*Requires #241.*
The Warp staff is functional, but lacks a user facing name, which makes it default to the internal name (IID_WARP). It also lacks a description, which makes it default to MH_I_WARP.
With the new functionality of being able to add and modify common strings, this gives the Warp staff a more readable name, albeit a bit meme-y. 🙃
> Adds a readable name and description for the Warp staff

- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9Randomizer.java
- Universal FE Randomizer/src/ui/MainView.java
- Universal FE Randomizer/src/ui/MiscellaneousView.java
- Universal FE Randomizer/src/ui/general/MessageModal.java
- Universal FE Randomizer/src/util/FreeSpaceManager.java
Added the ability to override the checksum check and directly specify the game when the checksum is unrecognized. This may allow some pre-modded games to be randomized, though the result cannot be guaranteed. It should mostly work if the code to load the characters, classes, or items remains unchanged, as the randomizer uses pointers to the tables instead of the raw table itself, but, its idea of what the IDs are will be still of the base game, so the result may not be as expected.
> Added checksum override option

- Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9Data.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ItemDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java
Fixed #237 - Added logic to make sure bosses can attack from both melee and range (when possible) and that they are not left with staves or only siege tomes.
> [Issue #237] Make sure bosses have appropriate attacking weapons

- Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9ChapterArmy.java
- Universal FE Randomizer/src/io/gcn/GCNISOHandler.java
- Universal FE Randomizer/src/io/gcn/GCNISOHandlerRecompilationDelegate.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ItemDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9Randomizer.java
Fixed #233 - Updated the Chapter 13 and 18 scripts to make sure Gatrie and Shinon's weapons upon rejoining match their new class (assuming their classes cannot Steel Lance and Brave Bow, respectively).
> [Issue #233] Updated script for Shinon and Gatrie's rejoining chapters

- Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9ChapterUnit.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ChapterDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9CharacterDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9Randomizer.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9RewardsRandomizer.java
- Universal FE Randomizer/src/ui/MiscellaneousView.java
- Universal FE Randomizer/src/ui/fe9/FE9ClassesView.java
- Universal FE Randomizer/src/ui/model/MiscellaneousOptions.java
- Universal FE Randomizer/src/util/OptionRecorder.java
Fixed #234 - Fixed an issue where minions between Chapters 13 and 17 were using special PIDs.
Also:
* Updated logic to make sure enemies with class-specific PIDs can only change to classes that have another corresponding PID.
* Added a new option to add random drops for enemies.
* Added a display string for the Daunt scroll.
> [Issue #234] Fixed minion randomization between Ch. 13 and Ch. 17

- Universal FE Randomizer/src/fedata/gba/GBAFEChapterData.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Chapter.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Chapter.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Chapter.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/random/gba/loader/ChapterLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #258 - Added logic to try and prevent overloading the sprite cache when randomizing minions in enemy-abundant chapters. (So far, only FE8's Ch. 20 is affected)
As the logic is fairly restrictive in the class selection, I've only applied this to one chapter in all of the GBAFE games, as it's the only chapter that exhibits this issue (at least the only one reported to have this issue). The theory is that, due to the large number enemies on the screen, randomizing minion classes randomly will likely increase the types of sprites on the map. This will overload the sprite cache and cause some graphics to become corrupted randomly. It's mostly an aesthetic issue, as the underlying data is should be fine. As far as I know, only FE8 exhibits this issue, and only if there are an abundance of …
> [Issue #258] Added restrictions to prevent sprite cache overload in Ch. 20

- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
Fixed #224 - Added a post-randomization step for FE6 to remove any lockpicks that might have been assigned to a non-playable non-thief unit, as they softlock the game.
> [Issue #224] Ensure no FE6 AI-controlled non-thief units have lockpicks

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #285 - Fixed an issue where the Random children option was not giving truly random children classes, instead limiting them to use the same weapon as their vanilla counterparts.
> [Issue #285] Fixed FE4 child randomization (Random option)

- Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9Data.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ItemDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9SkillDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java
Fixed #288 
* Added Vigilance and Insight to the skill randomization pool.
* Increased the chance of master seals from random rewards.
* Added SID_KEY0 to assassins by default.
* Decreased the Laguz->Beorc adjustment to 0.5x transform bonuses.
> [Issue #288] FE9 tweaks

- Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #161.
* Updated logic when randomizing recruitment to make sure shared slots have their bases set independently. This specifically allows character slots like Lyn/Lyn_tutorial to set their bases independently, instead of sharing the same bases.
* Updated the changelog for GBAFE to not de-duplicate characters for clarity. This makes it more clear what the stats are for multiple version of the same character.
> [Issue #161] Updated random recruitment logic with base stats

- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFEClassProvider.java
- Universal FE Randomizer/src/random/gba/loader/ClassDataLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
- Universal FE Randomizer/src/ui/ClassesView.java
- Universal FE Randomizer/src/ui/model/ClassOptions.java
- Universal FE Randomizer/src/util/OptionRecorder.java
Fixed #188 - Added an option when randomizing classes to disable cross-gender assignments. This takes precedence over force class change if necessary. The option also applies to all enemies and bosses if those are enabled.
> Added option to disable cross-gender assignments for class randomization.

- Universal FE Randomizer/src/util/recordkeeper/ChangelogSection.java
- Universal FE Randomizer/src/util/recordkeeper/ChangelogText.java
Fixed #276 - Added a newline in the ChangelogSection after each internal element for FE9 changelogs. This should resolve the issue where the changelog overflows and starts rendering tables on top of each other.
> Added newlines to FE9 Changelog to fix overflow display issues.

- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFECharacter.java
- Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #283 - Added logic to force weapons to the top slot for characters that have scripted battles. I think this is only an issue with FE6, but we'll do it for all of the GBA games.
> Fixed potential issue with Cecilia's scripted battle

- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
Fixed #319 - Added Artur to the list of characters needing range for FE8, due to the scripted fight in Ch. 4.
> Added Artur to the range lock list

- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #328 - Fixed an issue where it was possible to be assigned E rank for Dark Magic when Flux is D rank.
> Floor the minimum Dark weapon level to D rank instead of E rank

- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
- Universal FE Randomizer/src/ui/ClassesView.java
- Universal FE Randomizer/src/ui/WeaponsView.java
- Universal FE Randomizer/src/ui/model/ClassOptions.java
Fixed #300 - Added an option to adjust growths when randomizing classes so that their growths better fit their new class.
Also renamed some UI to make it less confusing.
> Personal Growths for Class Randomization

- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
- Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
- Universal FE Randomizer/src/ui/MiscellaneousView.java
- Universal FE Randomizer/src/ui/fe4/FE4ClassOptions.java
- Universal FE Randomizer/src/ui/fe4/FE4ClassesView.java
- Universal FE Randomizer/src/util/OptionRecorder.java
Fixed #345 - An option has been added to try to avoid duplicate class assignments when randomizing FE4 classes. This isn't a guarantee, due to the sheer number of other restrictions in place, but whenever possible, this option assigns a class that has not been assigned before. The pool resets between generations and substitutes have their own pool separate from the child character they replace.
> Added the option to assign classes evenly for FE4

- Universal FE Randomizer/src/random/gba/randomizer/GrowthsRandomizer.java
Fixed an issue (#356) where growths may not be randomized in some randomization setting combinations.
Growth randomization specifically has a special case where it generates growths only once for linked characters so that characters that have multiple versions (for example, FE7's tutorial version of Lyn and her non-tutorial counterpart) all share the same growths. This check is done by skipping over any character that is already modified. The assumption is that, coming into this randomization function, all previous work was already committed on the characters, which may not be the case, depending on the combination of settings given by the user. This simply forces character data to commit anything outstanding before starting, so that everything starts off as "not modified".
> [Issue #356] Fixed growth randomization not working.

- Universal FE Randomizer/src/fedata/gba/fe8/FE8SpellAnimationCollection.java
#360 - Fixed an issue where FE8 spell animations were not being set with little endian, causing us to write some weird (and obviously incorrect) animation values when assigning animations to weapons.
> [Issue #360] Fixed FE8 animation assignment issue

- Universal FE Randomizer/src/random/gba/randomizer/shuffling/data/FE6PortraitFormat.java
- Universal FE Randomizer/src/random/gba/randomizer/shuffling/data/FE7PortraitFormat.java
- Universal FE Randomizer/src/random/gba/randomizer/shuffling/data/FE8PortraitFormat.java
- Universal FE Randomizer/src/random/gba/randomizer/shuffling/data/PortraitFormat.java
- Universal FE Randomizer/src/util/GBAImageCodec.java
- Universal FE Randomizer/src/util/Size.java
Some of the Image Codec code was relying on a Windows-specific size structure. We want to keep Yune cross-platform, so we can't use anything that is locked to Windows. We just create a simple `Size` class that holds an integer width and height, since that seems to be all we need it to hold.
> Updated code to use a universal Size so we remain cross-platform.

- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
Small fix because when you selected to create a Prf during Randomized Recruitment the prf is always unbreakable, even if you select for it not to be
> Fix Random Recruitment Prfs always being Unbreakable

- Universal FE Randomizer/src/random/gba/randomizer/BasesRandomizer.java
Quick summary of how the "redistribute" bases randomizer for GBA works as I understand it: after summing a character's total personal bases (and randomly either adding or subtracting 0-variance points), earmark randomly between 2 and total/7+1 points for Luck. After that, keep picking a stat randomly (at 3 HP:2 Luck:1 anything else odd) and put randomly 1-3 points into that stat, then take it out of the base total.
On average, this procedure allocates a bit over 1/4 of a unit's personal bases (+2) to Luck. For units with personal bases beyond a sweet spot of ~30 total, this pretty dramatically overweights Luck, semi-routinely generating replacements for late prepromotes with 20+ Luck bases just because that's kind of what happens when you throw a 70+ base total in.
Best I can tell, this …
> "Redistribute" bases randomizer systematically assigns units too much Luck

- Universal FE Randomizer/src/fedata/gba/GBAFEChapterTargetedItemData.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Chapter.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6ChapterTargetedItem.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/random/gba/loader/ChapterLoader.java
This pretty much just ports the ITGC detection from FE7 to FE6. Might be helpful in the future? (I don't know if this affects the behavior of the randomizer at all; I was just using Yune as a way to extract them all to a list for myself.)
> Read list of targeted items in FE6 like in FE7

- Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ChapterDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9CharacterDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ClassDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ItemDataLoader.java
- Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9Randomizer.java
- Universal FE Randomizer/src/random/general/Randomizer.java
- Universal FE Randomizer/src/random/general/RandomizerListener.java
- Universal FE Randomizer/src/ui/MainView.java
- Universal FE Randomizer/src/util/recordkeeper/RecordBuilder.java
- Universal FE Randomizer/src/util/recordkeeper/RecordCategoryMap.java
- Universal FE Randomizer/src/util/recordkeeper/RecordEntry.java
- Universal FE Randomizer/src/util/recordkeeper/RecordHeader.java
- Universal FE Randomizer/src/util/recordkeeper/RecordInformation.java
- Universal FE Randomizer/src/util/recordkeeper/RecordKeeper.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/Base64Asset.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogAsset.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogBuilder.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogDivider.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogElement.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogHeader.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogImage.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogSection.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogStyleRule.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogTOC.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogTable.java
- Universal FE Randomizer/src/util/recordkeeper/fe9/ChangelogText.java
Contains a fix for Issue #178 to move bosses in GBA FE to their own section, by creating a subcategory "Characters - Bosses", which is pretty much the same thing FE4 does.
Additionally I moved the FE9 ChangeLog related things into their own package (recordkeeper.fe9) and refactored the GBA + FE4 Record Keeper into more of a Builder style like the FE9 one.
I personally prefer the readability as a builder, but if you disagree then I could remove those and only keep the change to the 
gba/loader/CharacterDataLoader.java
since that's the only thing needed for the defect
> Issue #178 + Proposed Refactor GBA + FE4 Record Keeper

- Universal FE Randomizer/src/random/gba/randomizer/service/GBASlotAdjustmentService.java
Fixed an issue where class bases were not being added to determine original bases during recruitment randomization, but were being subtracted at the end, leading to a lot of 0 bases for early game units.
> Fixed Randomized Recruitment bases

- Universal FE Randomizer/src/fedata/gba/GBAFEItemData.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Item.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Item.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Item.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFEItemProvider.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFEShop.java
- Universal FE Randomizer/src/fedata/gba/general/GBAFEShopProvider.java
- Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java
- Universal FE Randomizer/src/random/gba/loader/ShopLoader.java
- Universal FE Randomizer/src/random/gba/loader/StatboostLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/ShopRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/StatboosterRandomizer.java
- Universal FE Randomizer/src/random/general/WeightedDistributor.java
- Universal FE Randomizer/src/ui/LegacyViewContainer.java
- Universal FE Randomizer/src/ui/RandomizeButtonListener.java
- Universal FE Randomizer/src/ui/model/ShopOptions.java
- Universal FE Randomizer/src/ui/tabs/gba/GBAItemsTab.java
- Universal FE Randomizer/src/ui/views/CharacterShufflingView.java
- Universal FE Randomizer/src/ui/views/ShopView.java
- Universal FE Randomizer/src/util/DebugPrinter.java
- Universal FE Randomizer/src/util/OptionRecorder.java
- Universal FE Randomizer/src/util/WhyDoesJavaNotHaveThese.java
- Universal FE Randomizer/src/util/recordkeeper/RecordBuilder.java
- Universal FE Randomizer/src/util/recordkeeper/RecordCategoryMap.java
This Pull Request adds the ability to randomize shops with simple options available. Shops are pre-determined to be either Early game, Mid game, or Late game, with corresponding item pools. For the time being, this is all hard-coded, but maybe we can expose these levers if we can find a good way to specify them without overcomplicating it.
For the time being, weapons are largely determined by rank for when they show up. The early game pool is entirely made up of E rank weapons (and Flux). The mid-game pool includes D and C rank weapons. The late-game pool includes B and A rank weapons.
While shops are denoted as Early/Mid/Late game, they do not strictly use their corresponding pool. Instead, each stage of shop has a different distribution of which pool to use. These can be found in …
> Added Shop Randomization option

- Universal FE Randomizer/src/fedata/gba/GBAFEClassData.java
- Universal FE Randomizer/src/fedata/gba/GBAFEStatDto.java
- Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java
- Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java
- Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
- Universal FE Randomizer/src/fedata/gba/general/PaletteColor.java
- Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java
- Universal FE Randomizer/src/random/gba/loader/PaletteLoader.java
- Universal FE Randomizer/src/random/gba/loader/PaletteMapper.java
- Universal FE Randomizer/src/random/gba/loader/StatboostLoader.java
- Universal FE Randomizer/src/random/gba/randomizer/BasesRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/GrowthsRandomizer.java
- Universal FE Randomizer/src/random/gba/randomizer/StatboosterRandomizer.java
- Universal FE Randomizer/src/random/general/NormalDistributor.java
- Universal FE Randomizer/src/ui/general/OpenFileFlow.java
- Universal FE Randomizer/src/ui/model/BaseOptions.java
- Universal FE Randomizer/src/ui/model/GrowthOptions.java
- Universal FE Randomizer/src/ui/views/BasesView.java
- Universal FE Randomizer/src/ui/views/CharacterShufflingView.java
- Universal FE Randomizer/src/ui/views/GrowthsView.java
This pull request introduces a simplified option to get random growths and bases and attempts to approach it from a more holistic view, where characters are assigned more contextual growths based on their class. We do this by assigning a meaning to what it means to have an "Excellent", "Good", "Average", "Bad, "Abysmal" growth and bases in each area, in a rough normal distribution. Since the goal is to have one option you can just click and not think about too hard, this is what that actually breaks down as for each area.
Stat\Tier|Abysmal (Bottom 5%)|Bad (Next 25%)|Average (Middle 40%)|Good (Next 25%)|Excellent (Top 5%)
-|-|-|-|-|-
HP|45%|50% ~ 60%|65% ~ 80%|85% ~ 95%|100%
STR/SKL/SPD/LCK|20%|25% ~ 35%|40% ~ 60%|65% ~ 75%|80%
DEF/RES|5%|10% ~ 15%|20% ~ 35%|40% ~ 45%|50%
For example, a …
> Smart growths and Smart bases
