Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java, Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java, Universal FE Randomizer/src/fedata/gba/general/GBAFEItemProvider.java, Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java, Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #24 - Fixed an issue where member cards were getting lost if special inventory was required for characters holding them.
=> [Issue #24] Fixed Member Card not being assigned

Universal FE Randomizer/src/fedata/gba/fe6/FE6Item.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Item.java, Universal FE Randomizer/src/fedata/gba/fe8/FE8Item.java, Universal FE Randomizer/src/random/gba/loader/ChapterLoader.java, Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java, Universal FE Randomizer/src/random/gba/loader/ClassDataLoader.java, Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java, Universal FE Randomizer/src/random/gba/loader/TextLoader.java, Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #45 - Fixed an issue where randomizing recruitment also broke weapon effect text replacements.
=> [Issue #45] Fixed weapon effects

Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4PromotionRandomizer.java, Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
Added missing randomization options to FE4's changelog.
=> General cleanup and patched in the missing pieces from FE4's changelog.

Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java, Universal FE Randomizer/src/random/general/RelativeValueMapper.java, Universal FE Randomizer/src/ui/MainView.java, Universal FE Randomizer/src/ui/RecruitmentView.java, Universal FE Randomizer/src/ui/model/RecruitmentOptions.java
Fixed #33 - Added the ability to specify growth behavior when randomizing recruitment.
=> [Feature #33] Relative Growths

Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Implemented/Fixed #27 Updated logic to allow class randomization to result in the same class as the original.
This may fix #58, but I'm not sure how that could happen...
=> [Feature #27] Allowed randomization to result in same class in FE4

Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java, Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #66 - Made sure minions that are part of the Ch. 5 ending scene are not randomized.
=> [Issue #66] Blacklisted Ch. 5 ending scene minions from randomization.

Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #75 
* Fixed an issue where Magic -> Physical flip was using an incorrect condition.
* Moved the STR/MAG flip to occur after the holy blood adjustments.
=> [Issue #75] Fixed STR/MAG flip

Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java, Universal FE Randomizer/src/ui/RecruitmentView.java, Universal FE Randomizer/src/ui/model/RecruitmentOptions.java
Fixed #34 - Added the option to disable gender-locked randomized recruitment.
=> [Feature #34] Gender-swapped Randomized Recruitment

Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #71 - Make sure child characters receive a class that matches their gender.
=> [Issue #71] Ensure children receive a class matching their gender.

Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java
Fixed #59 - Revised logic for Seliph to make sure only his promoted class can use Sigurd's holy weapon, and not his base class.
=> [Issue #59] Fixed logic for Seliph's base and promoted class.

Universal FE Randomizer/src/fedata/gba/GBAFEClassData.java, Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java, Universal FE Randomizer/src/random/general/PoolDistributor.java, Universal FE Randomizer/src/ui/ClassesView.java, Universal FE Randomizer/src/ui/model/ClassOptions.java
Fixed #43 - Added option for class randomization on GBAFE to attempt to assign classes as evenly as possible. The new option is labeled "Assign Classes Evenly" under Randomize Playable Characters.
=> [Feature #43] Proportional Class Randomization

Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java, Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java
Fixed #105 - Fixed an issue where the logic to match rank was not used in the strict matching item assignment.
=> [Issue #105] Match Rank when using Strict Matching

Universal FE Randomizer/src/random/gba/randomizer/CharacterRandomizer.java
Fixed #106 - Fixed an issue where the minCON option was not being repsected.
=> [Issue #106] Fixed Minimum CON

Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/ui/ClassesView.java, Universal FE Randomizer/src/ui/MainView.java, Universal FE Randomizer/src/ui/model/ClassOptions.java
Fixed #106 - Added options for transferring bases when randomizing classes.
=> [Feature #106] Class Randomization - Bases Transfer options

Universal FE Randomizer/src/fedata/gba/GBAFEItemData.java, Universal FE Randomizer/src/fedata/gba/fe6/FE6Item.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Item.java, Universal FE Randomizer/src/fedata/gba/fe8/FE8Item.java, Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java, Universal FE Randomizer/src/util/recordkeeper/RecordKeeper.java
Fixed #111 
Changelog now has important notes per game regarding changes made or promotion items for special classes.
Emblem Bow in FE7 was also updated to have effectiveness against fliers (it had no effectiveness against anything before).
=> [Feature #111] Added Notes in Changelog

Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed #119 - Fixed an issue where healers were not always assigned a healing staff when retaining healers on class randomization.
=> [Issue #119] Fixed retained healers not getting healing staves

Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java, Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java, Universal FE Randomizer/src/fedata/gba/general/GBAFECharacter.java, Universal FE Randomizer/src/random/gba/loader/CharacterDataLoader.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java, Universal FE Randomizer/src/ui/RecruitmentView.java, Universal FE Randomizer/src/ui/model/RecruitmentOptions.java
Fixed #92 - Added class options for random recruitment for GBAFE. Also added the ability to include or exclude Lords, Thieves, and other Special Characters from randomized recruitment.
=> [Feature #92] GBAFE Recruitment Class Options

Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java, Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java, Universal FE Randomizer/src/fedata/gba/general/GBAFEClassProvider.java, Universal FE Randomizer/src/random/gba/loader/ClassDataLoader.java, Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java, Universal FE Randomizer/src/ui/ClassesView.java, Universal FE Randomizer/src/ui/model/ClassOptions.java
Fixed #127 - Added option to include or exclude special classes (and characters in those classes) from class randomization.
=> [Feature #127] Special Classes option for Class Randomization

Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/ui/ClassesView.java, Universal FE Randomizer/src/ui/EnemyBuffsView.java, Universal FE Randomizer/src/ui/MainView.java, Universal FE Randomizer/src/ui/model/ClassOptions.java
Fixed #97 - Added option to toggle force change for Class Randomization.
=> [Feature #97] Force Class Change option

Universal FE Randomizer/src/fedata/snes/fe4/FE4Data.java, Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4ClassRandomizer.java
Fixed an issue where some children were assuming they had major blood when they had minor blood.
Fixed an issue where Larcei may not be randomized.
=> [Issue] Fixed issues with children assuming major blood

Universal FE Randomizer/src/ui/MainView.java, Universal FE Randomizer/src/ui/fe9/FE9ClassesView.java, Universal FE Randomizer/src/ui/general/OpenFileFlow.java
* Addressed #219 - Added an "All Files" filter to the open file dialog window. This is in case your file extension isn't one of the common ones that I use (i.e. ISO for FE9, GBA for FE6, 7, and 8, and either SFC or SMC for FE4).
* Also bumped the version to 0.9.1 to prepare for release.
* Fixed a typo in the class randomization UI for FE9 (Force Class Chance -> Force Class Change)
=> [Enhancement #219] Added "All files" filter to the open file dialog window.

Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9ChapterArmy.java, Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9ChapterUnit.java, Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9Class.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ClassDataLoader.java, Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9Randomizer.java, Universal FE Randomizer/src/random/general/Randomizer.java, Universal FE Randomizer/src/random/snes/fe4/randomizer/FE4Randomizer.java, Universal FE Randomizer/src/ui/MainView.java, Universal FE Randomizer/src/util/DebugListener.java, Universal FE Randomizer/src/util/DebugPrinter.java
Added a console log that can be opened with CTRL+SHIFT+C in order to assist in debugging.
Fixed an issue where patch failure would silently fail instead of notifying the user.
Added logic for FE9 to allow Ragnell and the Regal Sword to be used by the class and not just Ike.
Added logic for FE9 to make sure only Ike has a scripted promotion regardless of his class instead of all Rangers.
=> Final Changes for 0.9.1 release.

Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9Data.java, Universal FE Randomizer/src/io/gcn/GCNCMPFileHandler.java, Universal FE Randomizer/src/io/gcn/GCNISOHandler.java, Universal FE Randomizer/src/io/gcn/GCNMessageFileHandler.java, Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9CommonTextLoader.java, Universal FE Randomizer/src/util/ByteArrayBuilder.java
Extended the ability of the CommonTextLoader to allow for modifications of common strings.
=> Added the ability to modify common strings.

Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9Class.java, Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ClassDataLoader.java
Fixed #250 - Fixed an issue where the method to add new class skills did not add the pointer to the pointer list in FE8Data.bin. This caused new class skills to not be applied, even if set.
=> [Issue #250] Fixed Ragnell and Regal Sword lock for Lord

Universal FE Randomizer/src/ui/MOVCONAffinityView.java
Issue #260 
As this widget is only used for GBAFE, we can simply change this value.
=> GBAFE: Increase max movement to 15

Universal FE Randomizer/src/util/DiffCompiler.java
Fixed #255 - Fixed an issue where Diffs that started before a batch of bytes and bled into the batch were not being applied. This manifested as some characters not getting the changes they're supposed to have. This for sure fixes Gatrie's and Lethe's growths not being applied, but it may also be the root cause of other bugs like Lethe's class change not applying and Rolf's incorrect models.
This probably also addresses bugs like #214 and #239
=> Fixed Gatrie's bugged growths (and probably Lethe/Rolf too)

Universal FE Randomizer/src/fedata/gcnwii/fe9/scripting/CallSceneByNameInstruction.java, Universal FE Randomizer/src/io/gcn/GCNCMBFileHandler.java, Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ChapterDataLoader.java, Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ClassDataLoader.java, Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ItemDataLoader.java, Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java, Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9Randomizer.java
Fixed #236 - Added more intelligent logic with the scripting instructions to replace Ike's starting four iron swords with four weapons he can actually use.
=> [Issue #236] Fixed Ike's starting weapon when using knives

Universal FE Randomizer/src/fedata/gcnwii/fe9/FE9Data.java
Fixed #292 - Fixed an issue where Feral Red Dragon (F) was not being assigned an AID, resulting in Shadow Ike.
=> [Issue #292] Fixed Feral Red Dragon (F) AID

Universal FE Randomizer/src/random/gba/randomizer/RecruitmentRandomizer.java
Fixed #168 - Updated logic to remove class restrictions for randomizing recruitment when using the slot class instead of the fill class, since using the slot classes makes the restrictions unnecessary.
=> [Issue #168] Remove restrictions on classes during recruitment randomization when using slot classes

Universal FE Randomizer/src/fedata/gba/fe6/FE6Item.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Item.java, Universal FE Randomizer/src/fedata/gba/fe8/FE8Item.java, Universal FE Randomizer/src/fedata/gba/general/WeaponEffects.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/WeaponsRandomizer.java, Universal FE Randomizer/src/random/gcnwii/fe9/loader/FE9ItemDataLoader.java, Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9WeaponRandomizer.java, Universal FE Randomizer/src/ui/WeaponEffectSelectionView.java, Universal FE Randomizer/src/ui/general/MinMaxControl.java, Universal FE Randomizer/src/ui/model/WeaponEffectOptions.java, Universal FE Randomizer/src/util/OptionRecorder.java
Fixed #170 - Added the ability to specify min/max crit range when adding High Critical as a weapon trait.
=> [Feature #170] Critical Ranges for High Critical weapon trait

Universal FE Randomizer/src/random/gba/loader/ClassDataLoader.java, Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #278 - Fixed an issue where Selena as a cutscene specific class was being overridden, causing crashes when playing the cutscene.
=> Fixed Chapter 10 Ephraim cutscene with Selena

Universal FE Randomizer/src/random/gba/loader/ClassDataLoader.java, Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/ui/ClassesView.java, Universal FE Randomizer/src/ui/EnemyBuffsView.java, Universal FE Randomizer/src/ui/RecruitmentView.java, Universal FE Randomizer/src/ui/model/ClassOptions.java
Fixed #326 - Added more options for better control over gender assignments when randomizing classes.
Also fixed a small issue with the UI for lord PRF weapons.
=> Added better control over gender options for class randomization

Universal FE Randomizer/src/random/gcnwii/fe9/randomizer/FE9ClassRandomizer.java
Fixed #312 - Fixed an issue where STR/MAG adjustment during class randomization was not being set properly.
=> Fixed an issue with STR/MAG adjustment during FE9 Class Randomization

Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java
Fixed #186 - Added logic to randomizing MOV for GBAFE so that you can never lose MOV from promotion.
=> Randomizing MOV ensures you never lose MOV on promotion

Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java, Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java, Universal FE Randomizer/src/fedata/gba/general/GBAFEItemProvider.java, Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/util/FreeSpaceManager.java
Fixed an issue with GBAFE where the newly created lord classes for the lords did not have effectiveness applied to them properly.
=> Fixed effectiveness not applying to newly created lord classes

Universal FE Randomizer/src/fedata/gba/fe6/FE6Data.java, Universal FE Randomizer/src/fedata/gba/fe7/FE7Data.java, Universal FE Randomizer/src/fedata/gba/fe8/FE8Data.java, Universal FE Randomizer/src/fedata/gba/general/GBAFEChapterMetadataChapter.java, Universal FE Randomizer/src/fedata/gba/general/GBAFEChapterMetadataData.java, Universal FE Randomizer/src/random/gba/loader/ChapterLoader.java, Universal FE Randomizer/src/random/gba/loader/ItemDataLoader.java, Universal FE Randomizer/src/random/gba/loader/PaletteLoader.java, Universal FE Randomizer/src/random/gba/randomizer/ClassRandomizer.java, Universal FE Randomizer/src/random/gba/randomizer/GBARandomizer.java, Universal FE Randomizer/src/ui/MiscellaneousView.java, Universal FE Randomizer/src/ui/general/MinMaxControl.java, Universal FE Randomizer/src/ui/model/MiscellaneousOptions.java, Universal FE Randomizer/src/util/OptionRecorder.java
Fixed #350 - Added the ability to process chapter metadata for GBAFE to add support for fog of war.
Also fixed some issues where promo items were still being assigned despite being disabled and fixed some FE6 palette issues.
=> Added options for fog of war.
